### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [viking2917/marie-de-france_lais_eugene-mason#1]
### General Issues:

- [x] The file names and id attributes need to match the file content. Since this work is made up of short stories, the file names and ids should be the story titles ([SEMOS 2.2.2](https://standardebooks.org/manual/1.7.0/single-page#2.2.2)).

- [x] A halftitle page is needed. See [SEMOS 6.5](https://standardebooks.org/manual/1.7.0/single-page#6.5) on how the file should be formatted.

- [x] After fixing all other issues, re-run `se build-title .`, `se build-manifest .`, `se build-spine .`, and `se build-toc .`

### chapter-1.xhtml:

- [x] This file name should be `introduction.xhtml`.

- [x] The file semantics should be:
```
	<body epub:type="frontmatter z3998:fiction">
		<section id="introduction" epub:type="introduction">
```

- [x] Remove the `<i>` element around i.e.

- [x] `Poésies de Marie de France` needs to be italicized and given book and language semantics ([SEMOS 5.3.1.2](https://standardebooks.org/manual/1.7.0/single-page#5.3.1.2)).

### chapter-2.xhtml:

- [x] This file name should be `prologue.xhtml`.

- [x] The file semantics should be:
```
		<section id="prologue" epub:type="prologue">
```

- [x] The title should be `<h2 epub:type="title">Prologue by Way of Dedication</h2>`.

### endnotes.xhtml:

- [x] Tag `Frêne` and `Coudre` as French. 

### content.opf:

- [x] Remove proper names from the short description.

**Comment by viking2917** [comment]
to confirm, when you say the prologue title should be _Prologue by Way of Dedication_, I should also remove the subtitle with text _By Way of Dedication_, correct?

**Comment by viking2917** [comment]
I proceeded with the assumption we should remove the subtitle, as the words would be duplicate otherwise. Can restore if that is the right thing...

**Comment by viking2917** [comment]
Thanks for the prompt and thorough review. I believe I have corrected all these issues, so another round of review is probably next? 

And should I close this issue or leave it til further review?

**Comment by EmmaSweeney** [comment]
> to confirm, when you say the prologue title should be Prologue by Way of Dedication, I should also remove the subtitle with text By Way of Dedication, correct?

Yes, there shouldn't be a subtitle.

**Comment by EmmaSweeney** [comment]
A few more things:

- [x] Re-run `se clean .` and commit the changes.

- [x] The files are no longer in the right order. You'll need to manually reorder the files in the `content.opf`'s `<spine>` then re-run `se build-toc .`

**Comment by viking2917** [comment]
Woof. Not sure how I bungled that, thanks for catching it!

I have pushed commits to address those issues, thanks!
